import {call,state,save,paidTool} from './spriteship.mjs';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const names=['Hearth Hall','Cottage','Lumber Camp','Stone Quarry','Gold Mine','Harvest Farm','Barracks','Ranger Lodge','Forge','Watchtower','Palisade'];
const tiers=[
  ['upgrades2','fortified ivory stone keep with copper roof, two small turrets and teal pennants; expanded timber cottage with an upper story; organized lumber workshop with large saw frame and stacked logs; expanded stone quarry shed with a stout wooden crane and stone blocks; reinforced gold mine headframe with a timber hoist and ore cart; larger farm with a copper-roof windmill and ordered wheat beds; fortified barracks with blue banners and stone training yard; expanded ranger lodge with green roof, balcony and archery targets; expanded stone forge with an orange furnace and metal bellows; two-level stone watchtower with copper roof and teal banner; strong timber palisade segment with stone end posts'],
  ['upgrades3','grand ivory stone hearth castle with copper roofs, three proud turrets, blue banners and glowing central hearth; elegant tall ivory stone and timber townhouse with copper roof; master lumber workshop with teal saw canopy and crane for logs; master quarry workshop with stone towers and a large lifting crane; master gold mine with reinforced metal headframe and golden ore crates; prosperous harvest farm with tall windmill and several golden wheat plots; elite ivory stone garrison with copper roofs and blue banners; master ranger hall with green roof, woodland banners and raised target range; great forge with tall copper chimneys, blazing furnace and anvil; imposing ivory stone battle tower with copper pointed roof and blue banners; reinforced stone-and-timber palisade wall segment with capped stone posts']
];
for(const [slug,description]of tiers){
  let s=await state();if(s.assets[slug])continue;
  const base=await call('get_asset',{assetId:s.assets.buildings.ids[0]});
  const r=await paidTool('art-'+slug,'create_asset',{projectId:s.project.id,assetType:'tileset',name:'Emberhold '+(slug==='upgrades2'?'veteran':'royal')+' structures',slug:'emberhold-'+slug,targetTileSize:512,referenceAssetUrls:[base.primaryUrl],prompt:'Exactly eleven distinct standalone upgrade buildings, separate complete transparent cutouts. Each subject appears once, no duplicates. Retain the reference sheet\'s consistent elevated angled topdown camera, refined hand-painted medieval fantasy style, ivory stone, copper roofs, Northwest lighting and physical proportions. These are visibly more developed versions of the eleven reference structures: '+description+'. Order: '+names.join(', ')+'. No landscape, no lettering, no gridlines. Every complete subject and ground contact visible.'});
  let attempts=0;
  for(;;){const j=await call('get_job',{jobId:r.jobId});console.log(slug,j.status);if(j.status==='error'){if(j.retryMode==='free'&&attempts<2){await paidTool('art-'+slug+'-free-recovery-'+(++attempts),'retry_job',{jobId:r.jobId});continue;}throw new Error(j.error);}if(j.status==='done'){s=await state();s.assets[slug]={ids:j.assetIds||j.gridAssetIds,jobId:r.jobId};await save(s);break;}await sleep(10000);}
}
